fos_elastica:
  clients:
    default: { host: '%env(ELASTICSEARCH_HOST)%', port: '%env(ELASTICSEARCH_PORT)%' }
  indexes:
    user:
      persistence:
        finder: ~
        driver: orm
        provider: ~
        model: App\Entity\User
      properties:
        username:
          type: text
        country:
          type: text
        city:
          type: text
        zip_code:
          type: text
        profile:
          type: object
          properties:
            bio:
              type: text
        userskill:
          type: object
          properties:
            skill_id:
              type: object
              properties:
                name:
                  type: text
                description:
                  type: text

    