fos_elastica:
  clients:
    default: { host: '%env(ELASTICSEARCH_HOST)%', port: '%env(ELASTICSEARCH_PORT)%' }
  indexes:
    user:
      settings:
        analysis:
          filter:
            ngram_filter:
              type: "ngram"
              min_gram: 3
              max_gram: 15
          analyzer:
            ngram_analyzer:
              type: custom
              tokenizer: standard
              filter: [lowercase, ngram_filter]
        index:
          max_ngram_diff: 12
      persistence:
        finder: ~
        driver: orm
        provider: ~
        model: App\Entity\User
      properties:
        username:
          type: text
          analyzer: ngram_analyzer
        country:
          type: text
          fields:
            raw:
              type: keyword
        city:
          type: text
          fields:
            raw:
              type: keyword
        zip_code:
          type: text
        profile:
          type: object
          properties:
            bio:
              type: text
              analyzer: ngram_analyzer
            musicStyles:
              type: text
        userProfessions:
          type: nested
          properties:
            profession:
              type: nested
              properties:
                id:
                  type: integer
                name:
                  type: text
        userEquipment:
          type: nested
          properties:
            equipment:
              type: nested
              properties:
                id:
                  type: integer
                brand:
                  type: text
                  analyzer: ngram_analyzer
                model:
                  type: text
                  analyzer: ngram_analyzer
                material:
                  type: nested
                  properties:
                    id:
                      type: integer
                    name:
                      type: text
                      analyzer: ngram_analyzer

    