version: "3.8"

services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./back:/var/www
    depends_on:
      - db
    environment:
      - PHP_EXTENSION_INSTALL=php-mysql
    build:
      context: ./back
      dockerfile: Dockerfile
    networks:
      - collab_net

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: colllab
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - collab_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - collab_net

  api:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx/api.conf:/etc/nginx/conf.d/default.conf
      - ./back/public:/var/www/public
    depends_on:
      - php
    networks:
      - collab_net

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - es_data:/usr/share/elasticsearch/data
  #   networks:
  #     - collab_net

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app/react-docker
      - /usr/src/app/front/node_modules
    # command: ["sh", "-c", "npm run build && npm start"]
    # command: ["sh", "-c", "npm run dev"]
    ports:
      - "3000:3000"
    depends_on:
      - php
    networks:
      - collab_net

volumes:
  db_data:
  es_data:

networks:
  collab_net:
